### ISSUE TITLE
Immediately accessing props passed to regl JSX?

### ISSUE THREAD

**Issue by gouldingken** [kevzettler/react-regl#40]
There may already be a way to do this, but I haven't been able to find it in any of the examples:

I'm trying to modify my shader code by passing in a '#define' value for an array length. As far as I know I can't use the regular  "uniforms" method of passing these values to my shader, so I typically use '#define' or const with a hard-coded value that I feed into my shader string.

Ideally this value would be a prop that I can pass to my React component and it would modify the shader code. I tried passing a value as a 'prop' (which seems very clean and React-friendly). But when I try to access the value on regl.prop - it returns a deferred-regl function expecting (context, props) and I'm not sure whether I can access the value at that point. 

Is there a way to do this currently? If not, it would be a really helpful feature.

FWIW I noticed [three.js uses a 'defines' object](https://threejs.org/docs/#api/en/materials/ShaderMaterial.defines) to abstract this further - but I don't think regl exposes that in the same way. 

```
const frag = (nArr) => {
    // language=GLSL
    return `
        precision mediump float;

        #define N_ARR ${nArr}
        #define MAX_STACK 2
       ...
```

```
const ColorizerRegl = regl({
    vert,
    frag: frag(regl.prop('nArr')),
    attributes: {
        position: [
            0, 4,
            -4, -4,
            4, -4,
        ]
    },

    uniforms: {
        textureReference: regl.prop('reference'),
        textureData: regl.prop('data'),
        textureCurrent: regl.prop('current'),
        dataWidth: regl.prop('dataWidth'),
    },

    count: 3
});
```

```
<ColorizerRegl nArr={metaData.nArr}
       reference={images.reference}
       data={images.data}
       current={images.current}
       dataWidth={metaData.dataWidth}/>
```

**Comment by kevzettler** [comment]
Hi @gouldingken 

you can pass a function to the `vert` and `frag` properties with signature `(context, props)` you can then return a shader string from the function and access the props. To access the prop will need to define the prop handle as a uniform like usual using `regl.prop`. 

Here is an example below that hacks the Triangle example to do the dynamic shader concatenation.

```
import React from 'react'
import regl, { ReglFrame } from '../../';

const Triangle = regl({
  vert: (context, props) => {
    return`
          precision mediump float;
          attribute vec2 position;
          #define test ${props.extra}
          void main () {
            gl_Position = vec4(position, 0, 1);
          }`
  },

  frag:`
          precision mediump float;
          uniform vec4 color;
          void main () {
            gl_FragColor = color;
          }`,
  attributes:{
    position: [
      [-1, 0],
      [0, -1],
      [1, 1]
    ]
  },

  uniforms:{
    color: [0.1, 1, 0, 1],
    extra: regl.prop('extra')
  },

  count: 3
});


export const ShaderProps = () => {
  return (
    <ReglFrame
      color={[0.1, 0.94921, 0.996, 1]}>
      <Triangle extra={'this_is_extra'}/>
    </ReglFrame>
  );
};
```

Let me know if this solution works for you. The use of the `uniforms` collection here is kinda weird and I like your note about the `defines` idea.

**Comment by gouldingken** [comment]
This is great! Thanks.

Will this also work for resolving regl images vs deferred image references? I ran into a similar problem with images where on the first render they resolve, but on the next render I'm getting errors related to invalid textures because the deferred methods are being passed through to the regl draw method. 

Apologies if this description is a bit vague. If helpful, I can post an example of what I'm talking about tomorrow.

**Comment by kevzettler** [comment]
@gouldingken yes please post an example on that image issue when you can. that unfortunately sounds like the issue from #31 Which maybe messy to resolve. 

but yes this same pattern of passing a `(context, props)` function will work for `attributes` and `uniforms` and can be more optimal.
