### ISSUE TITLE
How to access `regl.texture`

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [kevzettler/react-regl#6]
I was trying to replicate the Baboon texture example from http://regl.party/examples when I noticed that there is no simple way to reach `regl.texture` method in `react-regl`. Actually there is no way to reach the initialized `regl` object as far as I can tell. Am I missing something? Is there a built-in way to do this?

**Comment by kevzettler** [comment]
I have pushed a solution for this in `2.2.1`

you can check the texture example in the storybook at:

https://kevzettler.com/react-regl/?selectedKind=Geometry&selectedStory=Texture&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

If you initialize a uniform with `reglResourceType: 'texture'` it will initialize a resource behind the scenes
```
            tex: {
              reglResourceType: 'texture',
              width: pepperPNG.width,
              height: pepperPNG.height,
              data: pepperPNG.data,
              mag: 'linear',
              min: 'linear'
            }
```


I'm not 100% commited to this interface but works in the short term.
