### ISSUE TITLE
Add lodash as dependency

### ISSUE THREAD

**Issue by hydrosquall** [kevzettler/react-regl#8]
Based on this line,

https://github.com/kevzettler/react-regl/blob/56153852342f7b52d52fc41fab25dde2f949fc04/src/nodes/DrawNode.js#L5

, users need to install `lodash` separately for this library to work. The reason for my not opening a PR directly is in case you have an opinion about adding it as a core vs peer dependency.

**Comment by kevzettler** [comment]
Thanks @hydrosquall no opinion. core is fine. If you PR I will merge.

**Comment by kevzettler** [comment]
added in 23c334516ad93772531ab683afd9046a8b959959
